stages:
    - web-build

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew

web-build:
    stage: web-build
    script:
        - cd Backend/com-s-309-project
        - ./gradlew assemble
        - ./gradlew bootRun
