stages:
    - web-build

before_script:
    - cd Backend/com-s-309-project
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew

web-build:
    tags:
        - spring_backend
    stage: web-build
    script:
        - ./gradlew assemble
        - ./gradlew bootRun
