stages:
    - web-build

before_script:
    - cd Backend/com-s-309-project
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-devel-1.8.0.191.b12-0.el7_5.x86_64/
    - chmod +x ./gradlew

web-build:
    tags:
        - working_backend
    stage: web-build
    script:
        - ./gradlew assemble
        - ./gradlew bootRun
