stages:
    - cache
    - web-build
    - autodeploy

before_script:
    - cd Backend/com-s-309-project
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk/"
    - chmod +x ./gradlew

cache:
  paths:
     - .gradle/wrapper
     - .gradle/caches

web-build:
    tags:
        - working_backend
    stage: web-build
    script:
        - ./gradlew assemble
        - ./gradlew bootjar
        - sudo mv build/libs/*.jar /target/web-run.jar

autodeploy:
    tags:
        - working_backend
    stage: autodeploy
    script:
        - sudo systemctl stop systemWebRunner
        - sudo systemctl start systemWebRunner
